CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    id uuid NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE "AspNetUsers" (
    id uuid NOT NULL,
    removed_at_utc timestamp with time zone,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE courses (
    id uuid NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    removed_at_utc timestamp with time zone,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE schools (
    id uuid NOT NULL,
    name text NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    removed_at_utc timestamp with time zone,
    CONSTRAINT pk_schools PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoleClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    user_id uuid NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE ratings (
    id uuid NOT NULL,
    start integer NOT NULL,
    comment character varying(256),
    course_id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    removed_at_utc timestamp with time zone,
    CONSTRAINT pk_ratings PRIMARY KEY (id),
    CONSTRAINT fk_ratings_courses_course_id FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_ratings_user_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE students (
    user_id uuid NOT NULL,
    school_id uuid NOT NULL,
    associated_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (user_id, school_id),
    CONSTRAINT fk_students_schools_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE,
    CONSTRAINT fk_students_user_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

INSERT INTO schools (id, created_at_utc, name, removed_at_utc, updated_at_utc)
VALUES ('0e5bf386-d65c-4426-ab93-ae3f0ae8edc6', TIMESTAMPTZ '2024-06-10T21:42:46.197741Z', 'school admin', NULL, TIMESTAMPTZ '2024-06-10T21:42:46.197741Z');

CREATE INDEX ix_asp_net_role_claims_role_id ON "AspNetRoleClaims" (role_id);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON "AspNetUserClaims" (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON "AspNetUserLogins" (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON "AspNetUserRoles" (role_id);

CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalized_user_name);

CREATE INDEX ix_ratings_course_id ON ratings (course_id);

CREATE INDEX ix_ratings_id ON ratings (id);

CREATE INDEX ix_ratings_user_id_course_id ON ratings (user_id, course_id);

CREATE INDEX ix_schools_id ON schools (id);

CREATE INDEX ix_students_school_id ON students (school_id);

CREATE INDEX ix_students_user_id_school_id ON students (user_id, school_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20240610214246_InitialMigratil', '8.0.6');

COMMIT;